name: parku_movil
description: "Version Movil De ParkU"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

flutter_native_splash:
  color: "#39A900"
  image: assets/images/logo.png

  fullscreen: true

  android: true
  ios: true
  web: false

  android_12:
    color: "#39A900"
    image: assets/images/logo.png
    icon_background_color: "#39A900"